on:
  workflow_call:
    inputs:
      package_path:
        required: true
        description: The path to the package.json file to publish
        type: string
    secrets:
      GH_TOKEN:
        required: true
        description: Action provided github token
      NPM_TOKEN:
        required: true
        description: Npm token to use when publishing

permissions:
  contents: write

jobs:
  package-commit-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Npm install
        run: npm ci

      - name: build
        run: npm run build:all

      - name: Version and push
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: ${{ inputs.package_path }}
        with:
          minor-wording:  'add,new,feat'
          major-wording:  'breaking'
          patch-wording:  'patch,fix,chore,refactor,docs,test'
          skip-tag: true


      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          package: "${{ inputs.package_path }}package.json"
          token: ${{ secrets.NPM_TOKEN }}
